SupplyChainManagement/Controllers/YarnBookingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplyChainManagement.Db;
using SupplyChainManagement.DTO;
using SupplyChainManagement.Models;

namespace SupplyChainManagement.Controllers
{
    public class YarnBookingController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly SCMDbContext _context;

        public YarnBookingController(IConfiguration configuration, SCMDbContext context)
        {
            _configuration = configuration;

            _context = context;
        }
        public IActionResult Index()
        {
            var yarnbookingData = GetUnacknowledgedYarnBookingsAsync();
            var yarnSummary = _context.YarnBookingChilds
        .Join(_context.ItemMasters, c => c.ItemMasterId, im => im.ItemMasterId, (c, im) => new { c, im })
        .GroupBy(x => x.im.ItemName)
        .Select(g => new
        {
            YarnName = g.Key,
            TotalQuantity = g.Sum(x => x.c.Quantity)
        })
        .ToList();

            ViewBag.YarnSummary = yarnSummary;
            return View(yarnbookingData);
        }


        private List<YarnBookingMasterDto> GetUnacknowledgedYarnBookingsAsync()
        {
            var query = from yb in _context.YarnBookingMasters
                        join yc in _context.YarnBookingChilds on yb.YarnBookingMasterId equals yc.YarnBookingMasterId
                        join im in _context.ItemMasters on yc.ItemMasterId equals im.ItemMasterId
                        join fy in _context.FabricYarns on yc.ItemMasterId equals fy.YarnId
                        join fab in _context.ItemMasters on fy.FabricId equals fab.ItemMasterId
                        
                        select new
                        {
                            yb.YarnBookingMasterId,
                            yb.YarnBookingMasterNo,
                            FabricName = fab.ItemName,
                            YarnName = im.ItemName,
                            yb.IsAcknowledge,
                            Quantity = yc.Quantity,
                            yc.YarnBookingChildId,
                            yc.ItemMasterId
                        };

            var groupedData = query
                .GroupBy(x => new { x.YarnBookingMasterId, x.YarnBookingMasterNo, x.FabricName, x.IsAcknowledge })
                .Select(g => new YarnBookingMasterDto
                {
                    YarnBookingMasterId = g.Key.YarnBookingMasterId,
                    YarnBookingMasterNo = g.Key.YarnBookingMasterNo,
                    FabricName = g.Key.FabricName,
                    IsAcknowledge = g.Key.IsAcknowledge,
                    yarnBookingChildren = g.Select(x => new YarnBookingChildDto
                    {
                        YarnBookingChildId = x.YarnBookingChildId,
                        ItemMasterId = x.ItemMasterId,
                        YarnBookingMasterId=x.YarnBookingMasterId,
                        YarnName = x.YarnName,
                        Quantity = x.Quantity
                    }).ToList()
                })
                .ToList();

            return groupedData;
        }




        [HttpPost]
        public IActionResult Acknowledge([FromForm] int yarnBookingMasterId)
        {
            var booking = _context.YarnBookingMasters.FirstOrDefault(ym => ym.YarnBookingMasterId == yarnBookingMasterId);

            if (booking != null && booking.IsAcknowledge == 0)
            {
                booking.IsAcknowledge = 1;

                var bookingChildren = _context.YarnBookingChilds
                                      .Where(yc => yc.YarnBookingMasterId == yarnBookingMasterId)
                                      .Include(yc => yc.YarnBookingMaster)
                                      .AsEnumerable(); 

                var requisitions = new List<PurchaseRequisitionMaster>();

                foreach (var item in bookingChildren)
                {
                    var requisition = new PurchaseRequisitionMaster
                    {
                        PRNo = "PR-" + item.ItemMasterId,
                        PRDate = DateTime.Now,
                        ItemYarnId = item.ItemMasterId,
                        TotalQuantity = item.Quantity,
                        YarnBookingMasterId = yarnBookingMasterId,
                    };

                    _context.PurchaseRequisitionMasters.Add(requisition);
                    requisitions.Add(requisition);
                }

                _context.SaveChanges(); 

                foreach (var requisition in requisitions)
                {
                    requisition.PRNo = "PR-" + requisition.PurchaseRequisitionMasterId;
                }

                _context.PurchaseRequisitionMasters.UpdateRange(requisitions);
                _context.SaveChanges(); 

                return Ok();
            }

            return BadRequest("Unable to acknowledge booking.");
        }





        public IActionResult GetYarnSummary()
        {

            var yarnSummary = _context.YarnBookingChilds
            .Join(_context.YarnBookingMasters, c => c.YarnBookingMasterId, yb => yb.YarnBookingMasterId, (c, yb) => new { c, yb })
            .Join(_context.ItemMasters, combined => combined.c.ItemMasterId, im => im.ItemMasterId, (combined, im) => new { combined.c, im, combined.yb })
            .Where(x => x.yb.IsAcknowledge == 1) 
            .GroupBy(x => new { x.im.ItemMasterId, x.im.ItemName }) 
            .Select(g => new YarnBookingChildDto
            {
                ItemMasterId = g.Key.ItemMasterId, 
                YarnName = g.Key.ItemName, 
                TotalQuantity = g.Sum(x => x.c.Quantity) ,
                
            })
            .ToList();

            foreach (var summary in yarnSummary)
            {
               
                summary.yarnBookingDetails = GetYarnBookingDetails(summary.ItemMasterId);
            }

            return Json(yarnSummary);
        }


        public List<YarnBookingDetailsDto> GetYarnBookingDetails(int itemMasterId)
        {
            var yarnBookingDetails = _context.YarnBookingMasters
                .Join(_context.YarnBookingChilds, yb => yb.YarnBookingMasterId, yc => yc.YarnBookingMasterId, (yb, yc) => new { yb, yc })
                .Join(_context.ItemMasters, combined => combined.yc.ItemMasterId, im => im.ItemMasterId, (combined, im) => new { combined.yb, combined.yc, im })
                .Join(_context.FabricYarns, combined => combined.yc.ItemMasterId, fy => fy.YarnId, (combined, fy) => new { combined.yb, combined.yc, combined.im, fy })
                .Join(_context.ItemMasters, combined => combined.fy.FabricId, fab => fab.ItemMasterId, (combined, fab) => new { combined.yb, combined.yc, combined.im, combined.fy, fab })
                .Where(x => x.yc.ItemMasterId == itemMasterId) 
                .Select(x => new YarnBookingDetailsDto
                {
                    YarnBookingMasterId = x.yb.YarnBookingMasterId,
                    YarnBookingMasterNo = x.yb.YarnBookingMasterNo,
                    FabricId = x.fy.FabricId,
                    Fabric = x.fab.ItemName,
                    Quantity = x.yc.Quantity
                })
                
                .ToList();

            return yarnBookingDetails;
        }

        


    }
}

SupplyChainManagement/Views/YarnBooking/Index.cshtml
@model List<SupplyChainManagement.DTO.YarnBookingMasterDto>
@{
    ViewData["Title"] = "Yarn Booking";
}
<h2>Yarn Booking</h2></br>


    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="yarn-booking-tab" data-bs-toggle="tab" data-bs-target="#yarnBooking" type="button" role="tab" aria-controls="yarnBooking" aria-selected="true">Yarn Booking List</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="yarn-summary-tab" data-bs-toggle="tab" data-bs-target="#yarnSummary" type="button" role="tab" aria-controls="yarnSummary" aria-selected="false">Yarn Summary</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">

        <div class="tab-pane fade show active" id="yarnBooking" role="tabpanel" aria-labelledby="yarn-booking-tab">

            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Yarn Booking No</th>
                        <th>Fabric Name</th>
                        <th>Is Acknowledged</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var booking in Model)
                    {
                        <tr>
                            <td>
                                <button class="toggle-btn" onclick="toggleDetails('details-@booking.YarnBookingMasterId')">
                                    <i class="fa fa-chevron-down" aria-hidden="true"></i>
                                </button>
                            </td>
                            <td>@booking.YarnBookingMasterNo</td>
                            <td>@booking.FabricName</td>
                            <td>@(booking.IsAcknowledge == 1 ? "Yes" : "No")</td>
                            <td>
                                <button class="btn btn-success acknowledge-btn" data-id="@booking.YarnBookingMasterId" @(booking.IsAcknowledge == 1 ? "disabled" : "")>
                                    <i class="fa fa-check-circle"></i>
                                </button>
                            </td>
                        </tr>
                        <tr id="details-@booking.YarnBookingMasterId" class="child-details" style="display: none;">
                            <td colspan="5">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                           
                                            <th>Yarn Name</th>
                                            <th>Quantity</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var child in booking.yarnBookingChildren)
                                        {
                                            <tr>
                                                <td style="display:none">@child.YarnBookingMasterId</td>
                                                <td style="display:none">@child.YarnBookingChildId</td>
                                                <td style="display:none">@child.ItemMasterId</td>
                                                <td>@child.YarnName</td>
                                                <td>@child.Quantity</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="tab-pane fade" id="yarnSummary" role="tabpanel" aria-labelledby="yarn-summary-tab">
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Yarn Name</th>
                        <th>Total Quantity</th>
                    </tr>
                </thead>
                <tbody id="yarnSummaryBody">
                       
                </tbody>
            </table>
        </div>

    </div>

  




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function toggleDetails(detailsId) {
        var detailsRow = document.getElementById(detailsId);
        detailsRow.style.display = (detailsRow.style.display === "none") ? "table-row" : "none";
    }

    $(".acknowledge-btn").click(function () {
        var yarnBookingMasterId = $(this).data("id");
        if (!confirm("Are you sure you want to acknowledge this booking?")) return;
        $.ajax({
            url: '/YarnBooking/Acknowledge',
            type: 'POST',
            data: { yarnBookingMasterId: yarnBookingMasterId },
            success: function (response) {
                alert("Yarn Booking acknowledged successfully.");
                location.reload();
            },
            error: function (xhr) {
                alert("Failed to acknowledge the Yarn Booking. Please try again.");
            }
        });
    });

    $('#yarn-summary-tab').on('click', function () {
        $.ajax({
            url: '/YarnBooking/GetYarnSummary',
            type: 'GET',
            success: function (response) {
                console.log("Yarn Summary Data:", response);
                var tableBody = $('#yarnSummaryBody');
                tableBody.empty();
                response.forEach(function (item) {
                    var rowHtml = `<tr>
                            <td>
                                <button class="toggle-btn" onclick="toggleDetails('details-${item.itemMasterId}', this)">
                                    <i class="fa fa-chevron-down" aria-hidden="true"></i>
                                </button>
                            </td>
                            <td style="display: none;">${item.itemMasterId}</td>
                            <td>${item.yarnName}</td>
                            <td>${item.totalQuantity}</td>
                            
                        </tr>`;
                    tableBody.append(rowHtml);

                    
                    if (item.yarnBookingDetails && item.yarnBookingDetails.length > 0) {
                        var detailsRowHtml = `<tr id="details-${item.itemMasterId}" class="child-details" style="display: none;">
                                <td colspan="3">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th style="display: none;">Yarn Booking Master ID</th>
                                                <th>Yarn Booking No</th>
                                                <th>Fabric</th>
                                                <th>Quantity</th>
                                                    
                                            </tr>
                                        </thead>
                                        <tbody>`;
                        item.yarnBookingDetails.forEach(function (detail) {
                            detailsRowHtml += `<tr>
                                    <td style="display: none;">${detail.yarnBookingMasterId}</td>
                                    <td>${detail.yarnBookingMasterNo}</td>
                                    <td>${detail.fabric}</td>
                                    <td>${detail.quantity}</td>

                                </tr>`;
                        });
                        detailsRowHtml += '</tbody></table></td></tr>';
                        tableBody.append(detailsRowHtml);
                    }
                });
            },
            error: function () {
                alert('Failed to load yarn summary.');
            }
        });
    });
    
   

</script>



















































@* @model List<SupplyChainManagement.DTO.YarnBookingMasterDto>

<h2>Yarn Booking List</h2>


<div>
    <div style="float:left">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-light">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">

                <span class="fs-4"> </span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">


                <li>
                    <a asp-controller="Booking" asp-action="Index" class="nav-link link-dark">

                        Booking
                    </a>
                </li>
                <li>
                    <a asp-controller="YarnBooking" asp-action="Index" class="nav-link link-dark">

                        Yarn Booking
                    </a>
                </li>

            </ul>
            <hr>

        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Yarn Booking No</th>
                <th>Fabric Name</th>
                <th>Is Acknowledged</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var booking in Model)
            {
                <tr>
                    <td>
                        <button class="toggle-btn" onclick="toggleDetails('details-@booking.YarnBookingMasterId')">
                            <i class="fa fa-chevron-down" aria-hidden="true"></i>
                        </button>
                    </td>
                    <td>@booking.YarnBookingMasterNo</td>
                    <td>@booking.FabricName</td>
                    <td>@(booking.IsAcknowledge == 1 ? "Yes" : "No")</td>
                    <td>
                        <button class="btn btn-success acknowledge-btn" data-id="@booking.YarnBookingMasterId" @(booking.IsAcknowledge == 1 ? "disabled" : "")>
                            <i class="fa fa-check-circle"></i>
                        </button>
                    </td>
                </tr>


                <tr id="details-@booking.YarnBookingMasterId" class="child-details" style="display: none;">
                    <td colspan="4">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Yarn Name</th>
                                    <th>Quantity</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var child in booking.yarnBookingChildren)
                                {
                                    <tr>
                                        <td>@child.YarnName</td>
                                        <td>@child.Quantity</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function toggleDetails(detailsId) {
        var detailsRow = document.getElementById(detailsId);
        if (detailsRow.style.display === "none") {
            detailsRow.style.display = "table-row";
        } else {
            detailsRow.style.display = "none";
        }
    }


    $(".acknowledge-btn").click(function () {
        var yarnBookingMasterId = $(this).data("id");
        if (!confirm("Are you sure you want to acknowledge this booking?")) return;
        $.ajax({
            url: '/YarnBooking/Acknowledge',
            type: 'POST',
            data: { yarnBookingMasterId: yarnBookingMasterId },
            success: function (response) {
                alert("Yarn Booking acknowledged successfully.");
                location.reload();
            },
            error: function (xhr) {
                alert("Failed to acknowledge the Yarn Booking. Please try again.");
            }
        });
    });

</script>
 *@