SupplyChainManagement/Models/purchaseRequisition.cs
using System.ComponentModel.DataAnnotations;

namespace SupplyChainManagement.Models
{
    public class PurchaseRequisition
    {
        [Key]
        public long PRID { get; set; }
        public string PRNumber { get; set; }
        public DateTime? PRDate { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public string Requisitionar { get; set; }
        public string Supplier { get; set; }
        public string DeliveryUnit { get; set; }
        

        public List<PRDetails> ItemDetails { get; set; }
    }
}

SupplyChainManagement/Controllers/PurchaseRequisitionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplyChainManagement.Db;
using SupplyChainManagement.DTO;
using SupplyChainManagement.Models;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.Metrics;
using static System.Runtime.InteropServices.JavaScript.JSType;


namespace SupplyChainManagement.Controllers
{
    public class PurchaseRequisitionController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly string textile;
        private readonly string scm;
        private readonly DBService _queryService;
        private readonly SCMDbContext _context;
        public PurchaseRequisitionController(IConfiguration configuration, DBService DBService, SCMDbContext context)
        {
            _configuration = configuration;
            textile = _configuration.GetConnectionString("TextileConnection");
            scm = _configuration.GetConnectionString("DefaultConnection");
            _queryService = DBService;
            _context = context;
        }
        public IActionResult Index()
        {
            PRPending model = new PRPending();
            //model.EWOBookings = GetBookingsForEWO();
            model.PurchaseRequisitionMasterDtos = GetPR();


            return View(model);
        }

        public IActionResult Edit(int bookingId)
        {
            PurchaseRequisition model = new PurchaseRequisition();
            model.PRID = 0;
            model.PRNumber = "YPR" + bookingId;
            model.PRDate= DateTime.Now;
            model.Requisitionar = "Md.  Shiafur Rahman";
            model.DeliveryUnit = "Warehouse";
            model.ItemDetails = GetItems(bookingId);

            return View(model);
        }

         List<PRDetails> GetItems(int bookingId)
        {


            List<PRDetails> items = new List<PRDetails>();


            string textileQuery = $" select yn.YBookingNo,IM.ItemMasterID,im.DisplayItemName,sum(ch.BookingQty)qty,ShadeCode,u.UnitDesc from YarnBookingChild_New ch\r\n  inner join YarnBookingChildItem_New chi on chi.YBChildID=ch.YBChildID\r\n  left join EPYSL..ItemMaster IM ON  IM.ItemMasterID = ch.ItemMasterID\r\n  inner join EPYSL..Unit u on chi.UnitID=u.UnitID\r\ninner join YarnBookingMaster_New yn on yn.YBookingID=ch.YBookingID\r\n  where ch.YBookingID=" + bookingId + "  group by IM.ItemMasterID,im.DisplayItemName,ShadeCode,UnitDesc,yn.YBookingNo";

            var textileResults = _queryService.ExecuteQuery(textile, textileQuery);

            foreach (var reader in textileResults)
            {

                PRDetails item = new PRDetails();

                item.ItemMasterID = reader["ItemMasterID"] != DBNull.Value ? Convert.ToInt32(reader["ItemMasterID"]) : 0;
                item.ItemName = reader["DisplayItemName"] != DBNull.Value ? reader["DisplayItemName"].ToString() : string.Empty;
                item.PRQuantity = reader["qty"] != DBNull.Value ? Convert.ToInt32(reader["qty"]) : 0;
                item.ShadeCode = reader["ShadeCode"] != DBNull.Value ? reader["ShadeCode"].ToString() : string.Empty;
                item.UOM= reader["UnitDesc"] != DBNull.Value ? reader["UnitDesc"].ToString() : string.Empty;
                item.UnitPrice = 0;
                item.YBookingNo = reader["YBookingNo"] != DBNull.Value ? reader["YBookingNo"].ToString() : string.Empty;
                items.Add(item);


            }
            return items;


        }


        [HttpPost]
        public IActionResult SavePurchaseRequisition([FromBody] PurchaseRequisition model)
        {
            if (!ModelState.IsValid)
            {
                PurchaseRequisition purchaseRequisition = new PurchaseRequisition();
                purchaseRequisition.PRNumber = model.PRNumber;
                purchaseRequisition.PRDate = model.PRDate;
                purchaseRequisition.DeliveryDate = model.DeliveryDate;
                purchaseRequisition.DeliveryUnit = model.DeliveryUnit;
                purchaseRequisition.Supplier= model.Supplier;
                purchaseRequisition.Requisitionar= model.Requisitionar;



                _context.PurchaseRequisitions.Add(purchaseRequisition);
                _context.SaveChanges();
                var user = _context.PurchaseRequisitions.FirstOrDefault(i => i.PRNumber == purchaseRequisition.
                PRNumber);

                PRDetails purchaseDetails = new PRDetails();
                foreach (var item in model.ItemDetails)
                {
                   purchaseDetails.PurchaseRequisitionPRID= purchaseRequisition.PRID;
                    purchaseDetails.ItemMasterID = item.ItemMasterID;
                    purchaseDetails.UnitPrice = item.UnitPrice;
                    purchaseDetails.LeadTime = item.LeadTime;
                    purchaseDetails.UOM= item.UOM;
                    purchaseDetails.PRQuantity = item.PRQuantity;
                    purchaseDetails.ItemName = item.ItemName;
                    purchaseDetails.ShadeCode = item.ShadeCode;
                    _context.ItemDetails.Add(purchaseDetails);

                }
                _context.SaveChanges();

             
                return RedirectToAction("Index"); 
            }

            
            return View("Edit", model); 
        }

        public IActionResult GetPRInsight(int ItemMasterId)
        {


            List<ItemInsight> items = new List<ItemInsight>();


            string textileQuery = $"select top 10 ch.poqty poqty,rate,ch.QuotationRefNo,con.CountryName,ReceiveDate,po.DateAdded,\r\nc.Name from YarnPOChild ch \r\ninner join YarnPOMaster po on po.YPOMasterID = ch.YPOMasterID \r\ninner join YarnReceiveMaster rm on rm.POID=po.YPOMasterID\r\ninner join EPYSL..Contacts c on c.ContactID = po.SupplierID \r\ninner join EPYSL..country con on con.CountryID = CountryOfOriginID  where ItemMasterID = " + ItemMasterId + " order by po.DateAdded desc";

            var textileResults = _queryService.ExecuteQuery(textile, textileQuery);

            foreach (var reader in textileResults)
            {

                ItemInsight item = new ItemInsight();

                item.POQty = reader["poqty"] != DBNull.Value ? Convert.ToDecimal(reader["poqty"]) : 0;
                item.Rate = reader["rate"] != DBNull.Value ? Convert.ToDecimal(reader["rate"]) : 0;
                item.QuotationRefNo = reader["QuotationRefNo"] != DBNull.Value ? reader["QuotationRefNo"].ToString() : string.Empty;
                item.CountryName = reader["CountryName"] != DBNull.Value ? reader["CountryName"].ToString() : string.Empty;
                item.SupplierName = reader["Name"] != DBNull.Value ? reader["Name"].ToString() : string.Empty;
                item.POdate = reader["DateAdded"] != DBNull.Value ? reader["DateAdded"].ToString() : string.Empty;
                item.ReceivedDate = reader["ReceiveDate"] != DBNull.Value ? reader["ReceiveDate"].ToString() : string.Empty;
                items.Add(item);

                
            }
            // return Json(items);
            return PartialView("_ItemInsightPartial", items);



        }

        List<BookingInfo> GetBookingsForEWO()
        {
            List<BookingInfo> bookings = new List<BookingInfo>();


            string textileQuery = $"SELECT   distinct top 5 YBM.YBookingID, YBM.YBookingNo, FBM.ExportOrderID,FBM.BookingID ,BookingNo, c.Name,   FBM.BuyerTeamID  , StyleNo  \r\nFROM FBookingAcknowledge FBM\r\ninner join FBookingAcknowledgeChild FBC on FBC.AcknowledgeID = FBM.FBAckID\r\ninner join YarnBookingMaster_New YBM on  YBM.BookingID=FBM.BookingID\r\ninner join EPYSL..Contacts c  on c.ContactID = FBM.BuyerID\r\nwhere  FBM.ExportOrderID in (21747,23048,23068,23512,23975) order by FBM.ExportOrderID desc";

            var textileResults = _queryService.ExecuteQuery(textile, textileQuery);

            foreach (var reader in textileResults)
            {

                BookingInfo b = new BookingInfo();

                b.YBookingID = reader["YBookingID"] != DBNull.Value ? Convert.ToInt32(reader["YBookingID"]) : 0;
                b.ExportOrderID = reader["ExportOrderID"] != DBNull.Value ? Convert.ToInt32(reader["ExportOrderID"]) : 0;
                b.FabricBookingNo = reader["BookingNo"] != DBNull.Value ? reader["BookingNo"].ToString() : string.Empty;
                b.YarnBookingNo = reader["YBookingNo"] != DBNull.Value ? reader["YBookingNo"].ToString() : string.Empty;
                b.BuyerName = reader["Name"] != DBNull.Value ? reader["Name"].ToString() : string.Empty;
              
                b.StyleNo = reader["StyleNo"] != DBNull.Value ? reader["StyleNo"].ToString() : string.Empty;

                bookings.Add(b);


            }
            return bookings;

        }

        public List<PurchaseRequisitionMasterDto> GetPR()
        {
            List<PurchaseRequisitionMasterDto> prList = new List<PurchaseRequisitionMasterDto>();

            string textileQuery = @"select pr.PurchaseRequisitionMasterId,pr.PRNo,pr.PRDate,im.ItemName,pr.TotalQuantity from PurchaseRequisitionMasters pr
              inner join ItemMasters im on im.ItemMasterId=pr.ItemYarnId";

            var textileResults = _queryService.ExecuteQuery(scm, textileQuery);

            foreach (var reader in textileResults)
            {
                var pr = new PurchaseRequisitionMasterDto
                {
                    PurchaseRequisitionMasterId = reader["PurchaseRequisitionMasterId"] != DBNull.Value ? Convert.ToInt32(reader["PurchaseRequisitionMasterId"]) : 0,
                    PRNo = reader["PRNo"] != DBNull.Value ? reader["PRNo"].ToString() : string.Empty,
                    PRDate = reader["PRDate"] != DBNull.Value ? Convert.ToDateTime(reader["PRDate"]) : DateTime.MinValue,
                   
                    ItemName = reader["ItemName"] != DBNull.Value ? reader["ItemName"].ToString() : string.Empty,

SupplyChainManagement/Views/PurchaseRequisition/Edit.cshtml
@model PurchaseRequisition


<h2>@ViewData["Title"]</h2>

<form asp-action="SavePurchaseRequisition" method="post">
    <div class="col-md-12">

        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="PRNumber" class="control-label">PR Number</label>
                    <input asp-for="PRNumber" class="form-control" disabled />
                    <span asp-validation-for="PRNumber" class="text-danger"></span>
                </div>


            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="PRDate" class="control-label">PR Date</label>
                    <input asp-for="PRDate" class="form-control" type="date" disabled />
                    <span asp-validation-for="PRDate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="DeliveryDate" class="control-label">Delivery Date</label>
                    <input asp-for="DeliveryDate" class="form-control" type="date" />
                    <span asp-validation-for="DeliveryDate" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Requisitionar" class="control-label">Requisitionar </label>
                    <input asp-for="Requisitionar" class="form-control" disabled />
                    <span asp-validation-for="Requisitionar" class="text-danger"></span>
                </div>
            </div>

        </div>


        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="Supplier" class="control-label">Suggested Supplier</label>
                    <input asp-for="Supplier" class="form-control" />
                    <span asp-validation-for="Supplier" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="DeliveryUnit" class="control-label">Delivery Unit </label>
                    <input asp-for="DeliveryUnit" class="form-control" disabled />
                    <span asp-validation-for="DeliveryUnit" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <table id="itemTable" class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th></th>

                        <th class="text-center">Item Master Code</th>
                        <th class="text-center">Item Name</th>
                        <th class="text-center">Shade Code</th>
                        <th class="text-center">Lead Time</th>
                        <th class="text-center">PR Quantity</th>
                        <th class="text-center">UOM</th>
                        <th class="text-center">Suggested Unit Price</th>
                        <th class="text-center">Insight</th>


                    </tr>
                </thead>
                <tbody>
                    @{
                        var YBookingNo = string.Empty;
                    }
                    @if (Model.ItemDetails != null)
                    {
                        @foreach (var detail in Model.ItemDetails)
                        {
                            if (detail.YBookingNo != YBookingNo)
                            {

                                YBookingNo = detail.YBookingNo;
                                <tr class="table-secondary">
                                    <td colspan="10" class="text-center font-weight-bold">Yarn Booking: <strong>@detail.YBookingNo</strong></td>
                                </tr>
                            }
                            <tr id="itemRow_@detail.ItemMasterID">
                                <td class="text-center">

                                    <button type="button" class="btn btn-danger" onclick="deleteItem(@detail.ItemMasterID)">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </button>
                                </td>

                                <td class="text-center">@detail.ItemMasterID</td>
                                <td class="text-center">@detail.ItemName</td>
                                <td class="text-center">@detail.ShadeCode</td>
                                <td class="text-center">
                                    <input type="number" class="form-control leadTime" name="LeadTime" value="@detail.LeadTime" />
                                </td>
                                <td class="text-center">
                                    <input type="number" class="form-control PRQuantity" name="PRQuantity" value="@detail.PRQuantity" step="0.01" />
                                </td>
                                <td class="text-center">@detail.UOM</td>
                                <td class="text-center">
                                    <input type="number" class="form-control unitPrice" name="UnitPrice" value="@detail.UnitPrice" step="0.01" />
                                </td>
                                <td class="text-center">

                                    <button type="button" class="btn btn-info" onclick="showInsight(@detail.ItemMasterID)">
                                        <i class="fa fa-bar-chart" aria-hidden="true"></i>
                                    </button>
                                </td>


                            </tr>
                        }
                    }
                </tbody>
            </table>

        </div>
    </div>







    <input type="hidden" asp-for="PRID" />

    <button onclick="savePurchaseRequisition()" class="btn btn-primary">Save</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

<div class="modal fade" id="insightModal" tabindex="-1" role="dialog" aria-labelledby="insightModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="insightModalLabel">Item Insight</h5>
                <button type="button" class="close" onclick="closeInsightModal()" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="insightContent">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="closeInsightModal()">Close</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>



        function showInsight(itemMasterID) {
            $.ajax({
                url: '/PurchaseRequisition/GetPRInsight',
                type: 'GET',
                data: { itemMasterID: itemMasterID },
                success: function (result) {

                    $('#insightModal .modal-body').html(result);
                    $('#insightModal').modal('show');
                },
                error: function () {
                    alert("An error occurred while loading the insights.");
                }
            });
        }


        function closeInsightModal() {

            $('#insightModal').modal('hide');
        }


        function deleteItem(itemMasterID) {
            if (confirm("Are you sure you want to delete this item?")) {

                $('#itemRow_' + itemMasterID).remove();
                alert("Item deleted successfully.");
            }
        }



        function savePurchaseRequisition() {

            var requisition = {
                PRNumber: $('#PRNumber').val(),
                PRDate: $('#PRDate').val(),
                Supplier: $('#Supplier').val(),
                Requisitionar: $('#Requisitionar').val(),
                DeliveryDate: $('#DeliveryDate').val(),
                DeliveryUnit: $('#DeliveryUnit').val(),
                ItemDetails: []
            };


            $('#itemTable tbody tr').each(function () {
                var itemDetail = {
                    ItemMasterID: $(this).find('td:nth-child(2)').text().trim(),
                    ItemName: $(this).find('td:nth-child(3)').text().trim(),
                    ShadeCode: $(this).find('td:nth-child(4)').text().trim(),
                    LeadTime: $(this).find('.leadTime').val(),
                    PRQuantity: $(this).find('.PRQuantity').text().trim(),
                    UOM: $(this).find('td:nth-child(7)').text().trim(),
                    UnitPrice: $(this).find('.unitPrice').last().val()
                }


                requisition.ItemDetails.push(itemDetail);
            });


            $.ajax({
                url: '/PurchaseRequisition/SavePurchaseRequisition',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(requisition),
                success: function (response) {

                    alert('Purchase requisition saved successfully!');

                },
                error: function (error) {

                    alert('Error saving purchase requisition: ' + error.responseText);
                }
            });
        }




    </script>



}

SupplyChainManagement/Views/PurchaseRequisition/Index.cshtml
@model PRPending

@{
    ViewData["Title"] = "Purchase Requisition";
}
<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Order Base ( EWO)</button>
        @* <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Projection Base (Buyer)</button> *@
       @*  <button class="nav-link" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">
            Textile Capacity Base
            (ROL)
        </button> *@
    </div>
</nav>
</br>
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">


        <table class="table  table-striped">
            <thead class="thead-dark">
                <tr>
                    <th class="text-center">PR No</th>
                 
                    <th class="text-center">PR Date</th>
                    <th class="text-center">Item Name</th>
                    <th class="text-center">Total Quantity</th>
                    @* <th class="text-center">Action</th> *@
                </tr>
            </thead>
            <tbody>
                @if (Model.PurchaseRequisitionMasterDtos is not null)
                {
                    @foreach (var booking in Model.PurchaseRequisitionMasterDtos)
                    {
                        <tr>
                            <td>@booking.PRNo</td>
                         
                            <td>@booking.PRDate</td>
                            <td>@booking.ItemName</td>
                            <td>@booking.TotalQuantity</td>
                            @* <td class="text-center">

                                <a href="@Url.Action("Edit", "PurchaseRequisition", new { bookingId = booking.YBookingID })">
                                    <i class="fa fa-gear fa-spin" style="font-size:24px;color:green"></i>
                                </a>

                            </td> *@
                        </tr>
                    }
                
                
                }
    
            </tbody>
        </table>


    </div>
    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">



        <table class="table">
            <thead>
                <tr>
                    <th class="text-center">Yarn Booking</th>
                    <th class="text-center">Export Order</th>
                    <th class="text-center">Fabric Booking No</th>
                    <th class="text-center">Buyer Name</th>
                    <th class="text-center">BuyerTeamID</th>
                    <th class="text-center">StyleNo</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Projections is not null)
                {
                    @foreach (var booking in Model.Projections)
                    {
                        <tr>
                            <td>@booking.YarnBookingNo</td>
                            <td>@booking.ExportOrderID</td>
                            <td>@booking.FabricBookingNo</td>
                            <td>@booking.BuyerName</td>
                            <td>@booking.BuyerTeamID</td>
                            <td>@booking.StyleNo</td>
                            <td class="text-center"><i class="fa fa-gear fa-spin" style="font-size:24px;color:green"></i></td>
                        </tr>
                    }


                }

            </tbody>
        </table>











    </div>
    <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
</div>

SupplyChainManagement/Views/PurchaseRequisition/_ItemInsightPartial.cshtml
@model IEnumerable<ItemInsight>



<table class="table table-striped ">
    <thead class="thead-dark">
        <tr>
            <th class="text-center">PO Quantity</th>
            <th class="text-center">Rate</th>
            <th class="text-center">Quotation Ref No</th>
            <th class="text-center">Country Name</th>
            <th class="text-center">PO Date</th>
            <th class="text-center">Receive Date</th>
            <th class="text-center">Supplier Name</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
        {
            foreach (var insight in Model)
            {
                <tr>
                    <td class="text-center">@insight.POQty</td>
                    <td class="text-center">@insight.Rate</td>
                    <td class="text-center">@insight.QuotationRefNo</td>
                    <td class="text-center">@insight.CountryName</td>
                    <td class="text-center">
                        @DateTime.Parse(insight.POdate).ToString("MM/dd/yyyy")
                    </td>
                    <td class="text-center">@DateTime.Parse(insight.ReceivedDate).ToString("MM/dd/yyyy")</td>
                    <td class="text-center">@insight.SupplierName</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="5" class="text-center">No data available</td>
            </tr>
        }
    </tbody>
</table>