SupplyChainManagement/Models/POViewModel.cs
namespace SupplyChainManagement.Models
{
	public class POViewModel
	{
		public string? PONo { get; set; }
		public DateTime? PODate { get; set; }
		public string? SupplierName { get; set; }
		public decimal? Charges { get; set; }
		public string? CountryOfOrigin { get; set; }
		public int? ShippingTolerance { get; set; }
		public string? PortofLoading { get; set; }
		public string? PortofDischarge { get; set; }
		public string? ShipmentMode { get; set; }
		public List<YarnPOChild>? ItemDetails { get; set; }
	}
}

SupplyChainManagement/Controllers/POController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SupplyChainManagement.Db;
using SupplyChainManagement.DTO;
using SupplyChainManagement.Models;
using SupplyChainManagement.Service;

namespace SupplyChainManagement.Controllers
{
    public class POController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly string textile;
        private readonly string scm;
        private readonly DBService _queryService;
        private readonly SCMDbContext _context;
        private readonly MailServices _emailService;
 
        public POController(IConfiguration configuration, DBService DBService, SCMDbContext context ,MailServices mailServices)
        {
            _configuration = configuration;
            textile = _configuration.GetConnectionString("TextileConnection");
            scm = _configuration.GetConnectionString("DefaultConnection");
            _queryService = DBService;
            _context = context;
            _emailService = mailServices;
        }
        public IActionResult Index()
        {
            var result = (from po in _context.ItemPOMaster
                          join im in _context.ItemMasters on po.YPOMasterID equals im.ItemMasterId
                          select new ItemMasterPODto
                          {
                              YPOMasterID = po.YPOMasterID,
                              PONo = po.PONo,
                              CompanyName=po.CompanyName,
                              //PODate = (DateTime)po.PODate,
                              //ItemYarnId = pr.ItemYarnId,
                              ItemName = im.ItemName
                              
                          }).ToList();


            return View(result);
        }

        public IActionResult Add(int id) 
        {
            var masterData = _context.ItemPOMaster
                             .FirstOrDefault(m => m.YPOMasterID == id);

            

            var detailData = (from detail in _context.ItemPODetail
                              join master in _context.ItemMasters
                              on detail.ItemMasterID equals master.ItemMasterId
                              where detail.YPOMasterID == id
                              select new YarnPOChildDto
                              {
                                  ItemMasterID = detail.ItemMasterID,
                                  ItemName = master.ItemName,
                                  UnitName=detail.UnitName,
                                  BookingNo = detail.BookingNo,
                                  PoQty = detail.PoQty,
                                  Rate = detail.Rate,
                                  PIValue = detail.PIValue,
                                  Remarks = detail.Remarks
                              })
                 .ToList();

            var model = new YarnPOMasterDetailViewModel
            {
                YarnPOMaster = masterData,
                ItemDetails = detailData
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult SendPoEmail(int poId, string PONo, string supplierName, YarnPOMasterDetailViewModel model)
        {
			string linkURL = "http://localhost:5023/StandaloneApp/Index";
            var itemDetailsJson = Newtonsoft.Json.JsonConvert.SerializeObject(model.ItemDetails);
            string encryptedItemDetails = EncryptDecrypt.Encrypt(itemDetailsJson);
            var queryParameters = $"?PONo={model.YarnPOMaster.PONo}&PODate={model.YarnPOMaster.PODate:yyyy-MM-dd}&SupplierName={model.YarnPOMaster.SupplierName}&Charges={model.YarnPOMaster.Charges}&CountryOfOrigin={model.YarnPOMaster.CountryOfOrigin}&ShippingTolerance={model.YarnPOMaster.ShippingTolerance}&PortofLoading={model.YarnPOMaster.PortofLoading}&PortofDischarge={model.YarnPOMaster.PortofDischarge}&ShipmentMode={model.YarnPOMaster.ShipmentMode}&ItemDetails={Uri.EscapeDataString(encryptedItemDetails)}";
           
            string encryptedQueryData = EncryptDecrypt.Encrypt(queryParameters);
            string link = $"{linkURL}?data={Uri.EscapeDataString(encryptedQueryData)}";
           
            string emailBody = $"<p>Hello,</p><p>Please review the Purchase Order.</p><p><a href='{link}'>Click here to view PO {PONo}</a></p>";

            _emailService.SendEmail("noor.alam@epylliongroup.com", $"PO Notification for {supplierName}", emailBody);

            return RedirectToAction("Index");
        }

    }
}

SupplyChainManagement/Views/PO/Add.cshtml
@model SupplyChainManagement.DTO.YarnPOMasterDetailViewModel


<h2>@ViewData["Title"]</h2>
<style>
    .custom-label {
        font-weight: 600; 
        color: #333333; 
    }
</style>

<form asp-action="SavePurchaseRequisition" method="post">
    <div class="col-md-12">

        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.PONo" class="control-label custom-label">PO Number</label>
                    <input asp-for="YarnPOMaster.PONo" readonly class="form-control" />
                 
                </div>


            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.PODate" class="control-label custom-label">PO Date</label>
                    <input asp-for="YarnPOMaster.PODate"  class="form-control" type="date" />
                    
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.DeliveryStartDate" class="control-label custom-label">Delivery Start Date</label>
                    <input asp-for="YarnPOMaster.DeliveryStartDate"  class="form-control" type="date" />
                    
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.DeliveryStartDate" class="control-label custom-label">Delivery End Date</label>
                    <input asp-for="YarnPOMaster.DeliveryStartDate"  class="form-control" type="date" />
                    
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.SupplierName" class="control-label custom-label">Suppier Name </label>
                   @*  <input asp-for="YarnPOMaster.SupplierName"  class="form-control" /> *@
                    <select asp-for="YarnPOMaster.SupplierName" class="form-control" id="supplierDropdown">
                        <option value="">-- Select Supplier --</option>
                        <option value="Supplier1">Supplier-1</option>
                        <option value="Supplier2">Supplier-2</option>

                    </select>
 
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.Charges" class="control-label custom-label">Charges</label>
                    <input asp-for="YarnPOMaster.Charges" class="form-control" id="chargesInput" />
                   
                </div>


            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.CountryOfOrigin" class="control-label custom-label">Country</label>
                    <input asp-for="YarnPOMaster.CountryOfOrigin" class="form-control" id="countryInput" />
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.ShippingTolerance" class="control-label custom-label">Shipping Tolerance</label>
                    <input asp-for="YarnPOMaster.ShippingTolerance" class="form-control" type="number" id="toleranceInput" />
                   
                </div>
            </div>
            
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.PortofLoading" class="control-label custom-label">Portof Loading</label>
                    <input asp-for="YarnPOMaster.PortofLoading" class="form-control" id="portLoadingInput" />
                    
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.PortofDischarge" class="control-label custom-label">Portof Discharge </label>
                    <input asp-for="YarnPOMaster.PortofDischarge" class="form-control" id="portDischargeInput" />
                    
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="YarnPOMaster.ShipmentMode" class="control-label custom-label">Shipment Mode</label>
                    <input asp-for="YarnPOMaster.ShipmentMode" class="form-control" id="shipmentModeInput" />
                </div>
            </div>     
        </div>

      
        <br/><br/>
        <h4>Details Info </h4>
        <div class="row">
            <table id="itemTable" class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        
                       
                        <th class="text-center">Item Name</th>
                        
                        <th class="text-center">Unit</th>
                        <th class="text-center">PO Qty</th>
                        <th class="text-center">Rate</th>
                        <th class="text-center">Value</th>
                        <th class="text-center">Remarks</th>


                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.ItemDetails.Count; i++)
                    {
                        <tr>
                            @* <td class="text-center">
                                <input type="text" readonly name="ItemDetails[@i].BookingNo" value="@Model.ItemDetails[i].BookingNo" class="form-control" readonly />
                            </td> *@
                            <td class="text-center">
                                <input type="text" readonly name="ItemDetails[@i].ItemName" value="@Model.ItemDetails[i].ItemName" class="form-control" readonly />
                            </td>
                           
                            <td class="text-center">
                                <input type="text" readonly name="ItemDetails[@i].UnitName" value="@Model.ItemDetails[i].UnitName" class="form-control" readonly />
                            </td>
                            <td class="text-center">
                                <input type="number" readonly name="ItemDetails[@i].PoQty" value="@Model.ItemDetails[i].PoQty" class="form-control" readonly />
                            </td>
                            <td class="text-center">
                                <input type="number" name="ItemDetails[@i].Rate" value="@Model.ItemDetails[i].Rate" class="form-control" readonly />
                            </td>
                            <td class="text-center">
                                <input type="number" readonly name="ItemDetails[@i].PIValue" value="@Model.ItemDetails[i].PIValue" class="form-control" readonly />
                            </td>
                            <td class="text-center">
                                <input type="text"  name="ItemDetails[@i].Remarks" value="@Model.ItemDetails[i].Remarks" class="form-control"  />
                            </td>
                        </tr>
                    }
                </tbody>

            </table>

        </div>
    </div>

    <input type="hidden" asp-for="YarnPOMaster.YPOMasterID" />

    <button type="submit" formaction="@Url.Action("SendPoEmail", "PO")" formmethod="post" class="btn btn-primary">Release PO</button>
  
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>



        function showInsight(itemMasterID) {
            $.ajax({
                url: '/PurchaseRequisition/GetPRInsight',
                type: 'GET',
                data: { itemMasterID: itemMasterID },
                success: function (result) {

                    $('#insightModal .modal-body').html(result);
                    $('#insightModal').modal('show');
                },
                error: function () {
                    alert("An error occurred while loading the insights.");
                }
            });
        }


        function closeInsightModal() {

            $('#insightModal').modal('hide');
        }


        function deleteItem(itemMasterID) {
            if (confirm("Are you sure you want to delete this item?")) {

                $('#itemRow_' + itemMasterID).remove();
                alert("Item deleted successfully.");
            }
        }



        function savePurchaseRequisition() {

            var requisition = {
                PRNumber: $('#PRNumber').val(),
                PRDate: $('#PRDate').val(),
                Supplier: $('#Supplier').val(),
                Requisitionar: $('#Requisitionar').val(),
                DeliveryDate: $('#DeliveryDate').val(),
                DeliveryUnit: $('#DeliveryUnit').val(),
                ItemDetails: []
            };


            $('#itemTable tbody tr').each(function () {
                var itemDetail = {
                    ItemMasterID: $(this).find('td:nth-child(2)').text().trim(),
                    ItemName: $(this).find('td:nth-child(3)').text().trim(),
                    ShadeCode: $(this).find('td:nth-child(4)').text().trim(),
                    LeadTime: $(this).find('.leadTime').val(),
                    PRQuantity: $(this).find('.PRQuantity').text().trim(),
                    UOM: $(this).find('td:nth-child(7)').text().trim(),
                    UnitPrice: $(this).find('.unitPrice').last().val()
                }


                requisition.ItemDetails.push(itemDetail);
            });


            $.ajax({
                url: '/PurchaseRequisition/SavePurchaseRequisition',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(requisition),
                success: function (response) {

                    alert('Purchase requisition saved successfully!');

                },
                error: function (error) {

                    alert('Error saving purchase requisition: ' + error.responseText);
                }
            });
        }




    </script>



    <script>
        document.getElementById("supplierDropdown").addEventListener("change", function () {
            var selectedSupplier = this.value;

            var supplierData = {
                "Supplier1": {
                    charges: "100",
                    country: "USA",
                    tolerance: "5",
                    portLoading: "New York",
                    portDischarge: "Los Angeles",
                    shipmentMode: "Air"
                },
                "Supplier2": {
                    charges: "200",
                    country: "China",
                    tolerance: "10",
                    portLoading: "Shanghai",
                    portDischarge: "Beijing",
                    shipmentMode: "Sea"
                }
                
            };

            if (supplierData[selectedSupplier]) {
                document.getElementById("chargesInput").value = supplierData[selectedSupplier].charges;
                document.getElementById("countryInput").value = supplierData[selectedSupplier].country;
                document.getElementById("toleranceInput").value = supplierData[selectedSupplier].tolerance;
                document.getElementById("portLoadingInput").value = supplierData[selectedSupplier].portLoading;
                document.getElementById("portDischargeInput").value = supplierData[selectedSupplier].portDischarge;
                document.getElementById("shipmentModeInput").value = supplierData[selectedSupplier].shipmentMode;
            } else {

                document.getElementById("chargesInput").value = "";
                document.getElementById("countryInput").value = "";
                document.getElementById("toleranceInput").value = "";
                document.getElementById("portLoadingInput").value = "";
                document.getElementById("portDischargeInput").value = "";
                document.getElementById("shipmentModeInput").value = "";
            }
        });
    </script>

}

SupplyChainManagement/Views/PO/Index.cshtml
@model List<SupplyChainManagement.DTO.ItemMasterPODto>

@{
    ViewData["Title"] = "Purchase Requisition";
}
<a href="@Url.Action("Add", "PO")">
    <button class="btn btn-primary" style="display:none;">  Add PO</button>
</a>
</br></br>
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">


        <table class="table  table-striped">
            <thead class="thead-dark">
                <tr>
                    <th class="text-center">PO No</th>
                   
                    <th class="text-center">Item Name</th>
                    <th class="text-center">Unit Name</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var po in Model)
                {
                    <tr>

                        
                        <td>@po.PONo</td>
                        <td class="text-center">@po.ItemName</td>
                        <td>@po.CompanyName</td>
                        <td class="text-center">
                            <a href="@Url.Action("Add", "PO", new { id = po.YPOMasterID })">
                                Release

                            </a>
                        </td>
                        

                    </tr>
                }
               
            </tbody>
        </table>

    </div>
   
</div>

<div class="modal fade" id="insightModal" tabindex="-1" role="dialog" aria-labelledby="insightModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="insightModalLabel">Item Add</h5>
                <button type="button" class="close" onclick="closeInsightModal()" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="insightContent">
                <form id="poForm">
                    <div class="form-group">
                        <label for="poNo">PO No:</label>
                        <input type="text" class="form-control" id="poNo" placeholder="Enter PO No">
                    </div>
                    <div class="form-group">
                        <label for="poDate">PO Date:</label>
                        <input type="date" class="form-control" id="poDate">
                    </div>
                    <div class="form-group">
                        <label for="deliveryDate">Delivery Date:</label>
                        <input type="date" class="form-control" id="deliveryDate">
                    </div>
                    <div class="form-group">
                        <label for="supplierName">Supplier Name:</label>
                        <input type="text" class="form-control" id="supplierName" placeholder="Enter Supplier Name">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="savePoData()">Save</button>
                <button type="button" class="btn btn-secondary" onclick="closeInsightModal()">Close</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>



        function showInsight(itemMasterID) {
            $('#insightModal').modal('show');
            // $.ajax({
            //     url: '/PurchaseRequisition/GetPRInsight',
            //     type: 'GET',
            //     data: { itemMasterID: itemMasterID },
            //     success: function (result) {

            //         $('#insightModal .modal-body').html(result);
            //         $('#insightModal').modal('show');
            //     },
            //     error: function () {
            //         alert("An error occurred while loading the insights.");
            //     }
            // });
        }


        function closeInsightModal() {

            $('#insightModal').modal('hide');
        }


        function deleteItem(itemMasterID) {
            if (confirm("Are you sure you want to delete this item?")) {

                $('#itemRow_' + itemMasterID).remove();
                alert("Item deleted successfully.");
            }
        }



        function savePurchaseRequisition() {

            var requisition = {
                PRNumber: $('#PRNumber').val(),
                PRDate: $('#PRDate').val(),
                Supplier: $('#Supplier').val(),
                Requisitionar: $('#Requisitionar').val(),
                DeliveryDate: $('#DeliveryDate').val(),
                DeliveryUnit: $('#DeliveryUnit').val(),
                ItemDetails: []
            };


            $('#itemTable tbody tr').each(function () {
                var itemDetail = {
                    ItemMasterID: $(this).find('td:nth-child(2)').text().trim(),
                    ItemName: $(this).find('td:nth-child(3)').text().trim(),
                    ShadeCode: $(this).find('td:nth-child(4)').text().trim(),
                    LeadTime: $(this).find('.leadTime').val(),
                    PRQuantity: $(this).find('.PRQuantity').text().trim(),
                    UOM: $(this).find('td:nth-child(7)').text().trim(),
                    UnitPrice: $(this).find('.unitPrice').last().val()
                }


                requisition.ItemDetails.push(itemDetail);
            });


            $.ajax({
                url: '/PurchaseRequisition/SavePurchaseRequisition',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify(requisition),
                success: function (response) {

                    alert('Purchase requisition saved successfully!');

                },
                error: function (error) {

                    alert('Error saving purchase requisition: ' + error.responseText);
                }
            });
        }




    </script>



}